### ISSUE TITLE
Node <16 in package.json (v6r3 branch)

### ISSUE THREAD

**Issue by Bulmenisaurus** [projectsophon/darkforest-local#10]
https://github.com/projectsophon/darkforest-local/blob/57a66b604ee453ed79b55c0f233bfdba47f44754/package.json#L5

**Comment by phated** [comment]
Yes, the dark forest repos had this same requirement before round 4. See https://github.com/darkforest-eth/eth/blob/d531e3efb3db54a4f6bd2648c29d00c071264355/package.json#L51
