### ISSUE TITLE
Mined empty block range took too long & unfinished

### ISSUE THREAD

**Issue by gaozp** [projectsophon/darkforest-local#17]
![image](https://user-images.githubusercontent.com/3950594/178695149-3ac2db32-afc4-4a24-80b4-432f2be9d501.png)
It took so much time in mined empty block . Is there any way to short this process , or mock some block , because I just want to run it locally and play it myself.

**Comment by phated** [comment]
I'm not sure what your issue is, but it seems that your deploy process is not being run. The RPC server mines blocks on an interval (like a normal blockchain) and the deployment is supposed to happen when it is ready.

**Comment by gaozp** [comment]
@phated Thx for the answer . I tried 
`yarn start` 
again , and it works now . 
haha, I'm enjoying my game, thx for your work!
